"$schema" = 'https://starship.rs/config-schema.json'

format = "$character"
right_format = """
[â–‘â–’â–“](fg:#769ff0)\
$username\
$hostname\
$directory\
[î‚´](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[î‚´](fg:#394260 bg:#212734)\
$elixir\
$nodejs\
$c\
$rust\
$golang\
$php\
$java\
$kotlin\
$haskell\
$python\
$docker_context\
[î‚´ ](fg:#212734)"""

[os.symbols]
Windows = "ó°²"
Ubuntu = "ó°•ˆ"
SUSE = "ïŒ”"
Raspbian = "ó°¿"
Mint = "ó°£­"
Macos = "ó°€µ"
Manjaro = "ïŒ’"
Linux = "ó°Œ½"
Gentoo = "ó°£¨"
Fedora = "ó°£›"
Alpine = "ïŒ€"
Amazon = "ï‰°"
Android = "îœ"
Arch = "ó°£‡"
Artix = "ó°£‡"
CentOS = "ïŒ„"
Debian = "ó°£š"
Redhat = "ó±„›"
RedHatEnterprise = "ó±„›"

[hostname]
disabled = false
style = "bg:#769ff0 fg:#090c0c"
format = '[$ssh_symbol($hostname) ]($style)'
ssh_symbol = '@'

[username]
show_always = true
style_user = "bg:#769ff0 fg:#090c0c"
style_root = "bg:#769ff0 fg:#FF0c0c"
format = '[ $user@$hostname]($style)'

[directory]
style = "fg:#090c0c bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"

[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ó°š "
"Pictures" = "ï€¾ "
"Developer" = "ó°²‹ "

[git_branch]
symbol = "ï˜"
style = "bg:#394260 fg:#769ff0"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#394260 fg:#769ff0"
format = '[($all_status$ahead_behind )]($style)'

[elixir]
style = "fg:#a3aed2 bg:#212736"
format = '[ $symbol( $version \(OTP $otp_version\) ) ]($style)'
symbol = "â—‰"

[nodejs]
symbol = "îœ˜"
style = "bg:#a3aed2 fg:#212736"
format = '[ $symbol( $version ) ]($style)'

[rust]
symbol = "î¨"
style = "bg:#a3aed2 fg:#212736"
format = '[ $symbol( $version ) ]($style)'

[golang]
symbol = "î˜§"
style = "bg:#a3aed2 fg:#212736"
format = '[ $symbol( $version ) ]($style)'

[haskell]
symbol = "î˜Ÿ"
style = "bg:#a3aed2 fg:#212736"
format = '[ $symbol( $version ) ]($style)'

[python]
symbol = "î˜†"
style = "bg:#a3aed2 fg:#212736"
format = '[ $symbol( $version ) ]($style)'

[docker_context]
symbol = "ïŒˆ"
style = "bg:#a3aed2 fg:#212736"
format = '[ $symbol( $context) ]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#1d2230"
format = '[[ ïº $time ](fg:color_fg0 bg:color_bg1)]($style)'

[line_break]
disabled = true

[character]
disabled = false
success_symbol = '[ğŸ¤˜ âˆ‹](bold fg:aqua)'
error_symbol = '[ğŸ¤” âˆ‹](bold fg:red)'
vimcmd_symbol = '[ï´](bold fg:aqua)'
vimcmd_replace_one_symbol = '[ï´](bold fg:purple)'
vimcmd_replace_symbol = '[ï´](bold fg:purple)'
vimcmd_visual_symbol = '[ï´](bold fg:yellow)'
